# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Setup
title:               'Thoughts'
tagline:             'by Justin Etzine'
description:         'I\'m part of RPI\'s Class of 2018, pursuing a dual Bachelor of Science degree in Computer Science and Information Technology & Web Science. Check out my <a href="http://etz.io/">homepage</a>!'
url:                 'http://etz.io'
baseurl:             '/thoughts'


# Custom vars
version:             1.0.0
