# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Setup
title:               'Thoughts'
tagline:             'by Justin Etzine'
description:         'A blog by Justin Etzine '
url:                 'http://etz.io'
baseurl:             '/thoughts'


# Custom vars
version:             1.0.0
